name: Build APK Otomatis

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Ambil Kode
      uses: actions/checkout@v4

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Masuk ke folder proyek dan beri izin
      run: |
        cd MusicStream
        chmod +x gradlew

    - name: Proses Rakit APK
      run: |
        cd MusicStream
        ./gradlew assembleDebug

    - name: Simpan Hasil APK
      uses: actions/upload-artifact@v4
      with:
        name: MusikPlayer-Debug-APK
        path: MusicStream/app/build/outputs/apk/debug/app-debug.apk
